#!/usr/bin/env python3
"""Bounded input-checker controls; never builds or runs the compiler/corpus."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

PACKAGE = Path(__file__).resolve().parent


def mutate(raw, change, missing):
    rows = [line.split('\t') for line in raw.decode().splitlines()]
    if change == 'empty':
        return b''
    if change == 'missing-row':
        rows.pop()
    elif change == 'extra-row':
        rows.append(rows[0][:])
    elif change == 'duplicate-row':
        rows[1] = rows[0][:]
    elif change == 'reordered-rows':
        rows[0], rows[1] = rows[1], rows[0]
    elif change == 'unknown-label':
        rows[0][0] = 'unknown-case'
    elif change == 'altered-mode':
        rows[0][1] = 'project' if rows[0][1] == 'single' else 'single'
    elif change == 'nonexistent-source':
        rows[0][2] = str(missing)
    elif change == 'noncanonical-source':
        rows[0][2] += '/.'
    elif change == 'altered-row-limit':
        rows[0][3] = str(int(rows[0][3]) - 1)
    elif change == 'altered-byte-limit':
        rows[0][4] = str(int(rows[0][4]) - 1)
    elif change == 'extra-field':
        rows[0].append('extra')
    elif change == 'empty-field':
        rows[0][0] = ''
    elif change == 'missing-newline':
        return raw[:-1]
    elif change == 'invalid-utf8':
        return b'\xff' + raw
    elif change == 'oversized':
        return b'x' * (256 * 1024)
    else:
        raise ValueError(change)
    return ('\n'.join('\t'.join(row) for row in rows) + '\n').encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--authority-root', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    authority = args.authority_root.resolve(strict=True)
    out = args.output.resolve()
    out.mkdir(exist_ok=False)
    commands = []

    def invoke(argv, label):
        result = subprocess.run(argv, capture_output=True)
        (out / (label + '.stdout')).write_bytes(result.stdout)
        (out / (label + '.stderr')).write_bytes(result.stderr)
        commands.append({'argv': argv, 'exit': result.returncode})
        return result

    results = []
    # Both locations are generated by the unchanged prepare.py. No compiler API
    # or comparator is invoked; the copied .ox files remain inert input data.
    for label in ('requests', 'relocated-requests'):
        request = out / label
        result = invoke([sys.executable, '-B', str(PACKAGE / 'components/observer-v3/prepare.py'),
                         str(authority / 'contracts-v2'),
                         str(authority / 'element-boundary-supplement-v1'), str(request)],
                        label + '-prepare')
        if result.returncode:
            raise RuntimeError('request preparation failed; original logs retained')
        result = invoke([sys.executable, '-B', str(PACKAGE / 'verify_inputs.py'),
                         '--authority-root', str(authority), '--requests', str(request),
                         '--output', str(out / (label + '-good.json'))], label + '-good')
        if result.returncode:
            raise RuntimeError('valid relocated request rejected; original logs retained')
        receipt = json.loads((out / (label + '-good.json')).read_text())
        if receipt.get('request_tuple_counts') != {'core.tsv': 58, 'supplement.tsv': 6, 'observer-limits.tsv': 4}:
            raise RuntimeError('valid request receipt has wrong tuple counts')
        results.append({'id': label + '-good', 'accepted': True})
    request = out / 'requests'
    changes = ['empty', 'missing-row', 'extra-row', 'duplicate-row', 'reordered-rows',
               'unknown-label', 'altered-mode', 'nonexistent-source', 'noncanonical-source',
               'altered-row-limit', 'altered-byte-limit', 'extra-field', 'empty-field',
               'missing-newline', 'invalid-utf8', 'oversized']
    for name in ('core.tsv', 'supplement.tsv', 'observer-limits.tsv'):
        path = request / name
        original = path.read_bytes()
        for change in changes:
            label = name[:-4] + '-' + change
            body = mutate(original, change, out / 'does-not-exist')
            (out / (label + '.tsv')).write_bytes(body)
            path.write_bytes(body)
            receipt = out / (label + '.json')
            try:
                result = invoke([sys.executable, '-B', str(PACKAGE / 'verify_inputs.py'),
                                 '--authority-root', str(authority), '--requests', str(request),
                                 '--output', str(receipt)], label)
            finally:
                path.write_bytes(original)
            reason = ('request roster exceeds the historical input bound: ' if change == 'oversized'
                      else 'request tuple roster mismatch: ') + name
            rejected = (result.returncode != 0 and not receipt.exists()
                        and b'"PASS"' not in result.stdout and reason.encode() in result.stderr)
            results.append({'id': label, 'rejected': rejected, 'input_sha256': hashlib.sha256(body).hexdigest()})
    (out / 'commands.json').write_text(json.dumps(commands, indent=2) + '\n')
    rejected = sum(row.get('rejected', False) for row in results)
    report = {'schema': 'oxid-unit3a-request-identity-controls-v1', 'positive': 2,
              'negative_rejected': rejected, 'negative_total': 48,
              'compiler_runs': 0, 'semantic_comparisons': 0, 'controls': results}
    (out / 'report.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps({key: report[key] for key in ('positive', 'negative_rejected', 'negative_total',
                                                'compiler_runs', 'semantic_comparisons')}))
    if rejected != 48:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
