[package]
name = "oxid"
version = "0.9.0"
edition = "2021"
build = "build.rs"
autobins = false
description = "Fast standalone Oxid language runtime and toolchain"
license = "MIT"

[[bin]]
name = "oxid"
path = "src/cli.rs"

[dependencies]
libc = "=0.2.177"
sha2 = "=0.10.9"

[build-dependencies]
cc = "1"
